package com.softserve.edu.items.entity;

public enum SqlQueries {
	CREATE_DATABASE,
	CREATE,
	INSERT,
	INSERT_USER_MOVIE,
	GET_BY_ID,
	GET_BY_TWO_ID,
	GET_BY_FIELD,
	GET_ALL,
	GET_ALL_USER_MOVIES,
	GET_USER_MOVIES_OFFSET,
	GET_ALL_ORDER_BY,
	GET_USER_MOVIES,
	GET_BY_TITLE_AND_NOT_ID,
	SEARCH,
	UPDATE_BY_ID,
	UPDATE_BY_FIELD,
	DELETE_BY_ID,
	DELETE_BY_FIELD;
}
